table DimCustomer
	lineageTag: 04a73281-aa9c-44be-865c-ebd0d65bc00c
	sourceLineageTag: [dbo].[DimCustomer]

	measure TotalSales = CALCULATE(SUM(FactSalesOrder[SalesTotal]))
		formatString: 0
		lineageTag: 918b6424-db39-4eab-a907-90d5cd803293

		changedProperty = Name

	column CustomerKey
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: d97ec087-129c-4758-8f4c-f198624c3fb1
		sourceLineageTag: CustomerKey
		summarizeBy: none
		sourceColumn: CustomerKey

		annotation SummarizationSetBy = Automatic

	column CustomerAltKey
		dataType: string
		sourceProviderType: varchar(50)
		lineageTag: cb9cf384-672d-4544-850c-842ee20d1312
		sourceLineageTag: CustomerAltKey
		summarizeBy: none
		sourceColumn: CustomerAltKey

		annotation SummarizationSetBy = Automatic

	column Title
		dataType: string
		sourceProviderType: varchar(5)
		lineageTag: a0515e82-cf5b-4444-b239-c0ff40007d9d
		sourceLineageTag: Title
		summarizeBy: none
		sourceColumn: Title

		annotation SummarizationSetBy = Automatic

	column FirstName
		dataType: string
		isHidden
		sourceProviderType: varchar(50)
		lineageTag: de6d9022-2fc1-4f79-bc19-4aa0f523bbaf
		sourceLineageTag: FirstName
		summarizeBy: none
		sourceColumn: FirstName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column LastName
		dataType: string
		isHidden
		sourceProviderType: varchar(50)
		lineageTag: be5aeb10-9075-493d-89cd-274981a4b13b
		sourceLineageTag: LastName
		summarizeBy: none
		sourceColumn: LastName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column AddressLine1
		dataType: string
		sourceProviderType: varchar(200)
		lineageTag: 9dbb5485-c810-4791-9dc5-93853b512517
		sourceLineageTag: AddressLine1
		summarizeBy: none
		sourceColumn: AddressLine1

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		sourceProviderType: varchar(50)
		lineageTag: 240cb617-56e6-4637-a6ea-48bd007998e5
		sourceLineageTag: City
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column StateProvince
		dataType: string
		sourceProviderType: varchar(50)
		lineageTag: d40d285f-535f-4c8f-9eb7-06b053d0b8f9
		sourceLineageTag: StateProvince
		summarizeBy: none
		sourceColumn: StateProvince

		annotation SummarizationSetBy = Automatic

	column CountryRegion
		dataType: string
		sourceProviderType: varchar(50)
		lineageTag: fe567254-aed3-4818-9c0c-491939c5b704
		sourceLineageTag: CountryRegion
		summarizeBy: none
		sourceColumn: CountryRegion

		annotation SummarizationSetBy = Automatic

	column PostalCode
		dataType: string
		sourceProviderType: varchar(20)
		lineageTag: 545cb4db-1f1d-4eda-82d2-fbfeb3d59856
		sourceLineageTag: PostalCode
		summarizeBy: none
		sourceColumn: PostalCode

		annotation SummarizationSetBy = Automatic

	partition DimCustomer = entity
		mode: directLake
		source
			entityName: DimCustomer
			schemaName: dbo
			expressionSource: DatabaseQuery

	annotation PBI_ResultType = Table

